-- Amplia CRM_ESCALADO para permitir até 3 médicos (CRM+UF separados por |)
IF COL_LENGTH('ESCALAMEDICA', 'CRM_ESCALADO') IS NOT NULL
BEGIN
  ALTER TABLE ESCALAMEDICA ALTER COLUMN CRM_ESCALADO VARCHAR(100) NOT NULL;
END
GO
