-- ESCALA MEDICA - NOVAS TABELAS (projeto Node standalone)

CREATE TABLE ESCALAMEDICA (
    IDPLANTAO INT IDENTITY(1,1) PRIMARY KEY,
    CODFILIAL INT NOT NULL,
    EMPRESA INT NOT NULL,
    CODCCUSTO VARCHAR(30) NOT NULL,
    DATA DATE NOT NULL,
    HORAINICIO TIME NOT NULL,
    HORAFIM TIME NOT NULL,
    IDESPECIALIDADE INT NOT NULL,
    CODTIPOPLANTAO INT NOT NULL,
    CRM_ESCALADO VARCHAR(200) NOT NULL, -- até 3 médicos: CRM+UF separados por |
    STATUS VARCHAR(25) NOT NULL DEFAULT 'ABERTO', -- ABERTO, EM_ANDAMENTO, CONCLUIDO, CANCELADO, PENDENTE_JUSTIFICATIVA
    DATAEXPIRACAO DATETIME NULL,
    RECCREATEDBY VARCHAR(50) NOT NULL,
    RECCREATEDON DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE ESCALATROCA (
    IDTROCA INT IDENTITY(1,1) PRIMARY KEY,
    IDPLANTAO INT NOT NULL FOREIGN KEY REFERENCES ESCALAMEDICA(IDPLANTAO),
    CRM_ORIGINAL VARCHAR(20) NOT NULL,
    CRM_NOVO VARCHAR(20) NOT NULL,
    DATAALTERACAO DATETIME NOT NULL DEFAULT GETDATE(),
    ALTERADOPOR VARCHAR(50) NOT NULL,
    STATUSAPROVACAO VARCHAR(15) NOT NULL DEFAULT 'PENDENTE', -- PENDENTE, APROVADO, REPROVADO, N.A
    APROVADOPOR VARCHAR(50) NULL,
    DATAAPROVACAO DATETIME NULL
);

CREATE TABLE JUSTIFICATIVAAUSENCIA (
    IDJUSTIFICATIVA INT IDENTITY(1,1) PRIMARY KEY,
    IDPLANTAO INT NOT NULL FOREIGN KEY REFERENCES ESCALAMEDICA(IDPLANTAO),
    CRM VARCHAR(20) NOT NULL,
    TIPOAUSENCIA VARCHAR(30) NOT NULL, -- ENTRADA_NAO_REGISTRADA, SAIDA_NAO_REGISTRADA, PLANTAO_INTEIRO
    DATAHORAREAL DATETIME NULL,
    MOTIVO VARCHAR(MAX) NOT NULL,
    STATUSAPROVACAO VARCHAR(15) NOT NULL DEFAULT 'PENDENTE',
    APROVADOPOR VARCHAR(50) NULL,
    DATAAPROVACAO DATETIME NULL,
    RECCREATEDON DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE REGISTROACESSO (
    IDREGISTRO INT IDENTITY(1,1) PRIMARY KEY,
    IDPLANTAO INT NOT NULL FOREIGN KEY REFERENCES ESCALAMEDICA(IDPLANTAO),
    TIPO VARCHAR(10) NOT NULL, -- ENTRADA, SAIDA
    DATABATIDA DATE NOT NULL,
    HORABATIDA TIME NOT NULL,
    CRM VARCHAR(20) NOT NULL,
    RECCREATEDON DATETIME NOT NULL DEFAULT GETDATE()
);

-- PERFIS DE ACESSO (ligados a FDN_USERTENANT.LOGIN, que fica no banco do Fluig) - Admin e Administrativo
CREATE TABLE USUARIOPERFIL (
    IDUSUARIOPERFIL INT IDENTITY(1,1) PRIMARY KEY,
    LOGIN VARCHAR(100) NOT NULL UNIQUE, -- corresponde a FDN_USERTENANT.LOGIN
    PERFIL VARCHAR(20) NOT NULL, -- ADMIN, ADMINISTRATIVO
    ATIVO BIT NOT NULL DEFAULT 1,
    RECCREATEDON DATETIME NOT NULL DEFAULT GETDATE()
);

-- UNIDADES GERENCIADAS POR CADA USUARIO ADMINISTRATIVO (ADMIN gerencia todas, nao precisa de linha)
CREATE TABLE USUARIOUNIDADE (
    IDUSUARIOUNIDADE INT IDENTITY(1,1) PRIMARY KEY,
    IDUSUARIOPERFIL INT NOT NULL FOREIGN KEY REFERENCES USUARIOPERFIL(IDUSUARIOPERFIL),
    CODFILIAL INT NOT NULL
);
